branch-defaults:
  default:
    environment: random-backend-dev2
    group_suffix: null
global:
  application_name: random-backend
  branch: null
  default_ec2_keyname: aws-eb-random-back
  default_platform: Python 3.8 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
